---
- name: trust docker gpg
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    state: present
    update_cache: yes

- name: install docker packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
   - docker-ce  
   - docker-ce-cli
   - docker-compose
   - containerd.io
